// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7c2ce507-8474-41e1-b740-15a9a7181490",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZGzmE5hAb",
    "aws_user_pools_web_client_id": "qcpvj1rtm3rmmc8cl7eonra1v",
    "oauth": {},
    "aws_user_files_s3_bucket": "endcancer-files-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
